# fly.toml app configuration file generated for fiicalculator on 2023-08-15T21:11:32-03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "fiicalculator"
primary_region = "gru"
kill_signal = "SIGTERM"

[build]

[env]
  FLY_LAUNCH_MODE = "clone"
  PHX_HOST = "fiicalculator.fly.dev"
  PORT = "8080"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1
  processes = ["app"]
  [http_service.concurrency]
    type = "connections"
    hard_limit = 1000
    soft_limit = 1000
